// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnBT1hdLM_DtuwxrGuoW5ahym0HA3OleQ',
    appId: '1:209089815540:web:e306f78da6e969a7950fa1',
    messagingSenderId: '209089815540',
    projectId: 'crud-c6238',
    authDomain: 'crud-c6238.firebaseapp.com',
    storageBucket: 'crud-c6238.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOgYeTGCSoCKfBNTpqlvj6g7gKGf9JsU',
    appId: '1:209089815540:android:f5b54b4a0a2bdb13950fa1',
    messagingSenderId: '209089815540',
    projectId: 'crud-c6238',
    storageBucket: 'crud-c6238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4vNqRNZDLsPw6RXxT40bhhVY1rTl2KNQ',
    appId: '1:209089815540:ios:c5a3eec6436e3603950fa1',
    messagingSenderId: '209089815540',
    projectId: 'crud-c6238',
    storageBucket: 'crud-c6238.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4vNqRNZDLsPw6RXxT40bhhVY1rTl2KNQ',
    appId: '1:209089815540:ios:f522a92155906737950fa1',
    messagingSenderId: '209089815540',
    projectId: 'crud-c6238',
    storageBucket: 'crud-c6238.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
